### ISSUE TITLE
ERROR scanning old repository on restart of beta 5

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom-proxy#17]
at java.time.format.DateTimeParseException: Text 'FEED_NAME_SAMPLE' could not be parsed at index 0
at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
at java.time.format.DateTimeFormatter.parseBest(DateTimeFormatter.java:1897)
at stroom.proxy.util.date.DateUtil.parse(DateUtil.java:86)
at stroom.proxy.util.date.DateUtil.parseNormalDate(DateUtil.java:144)
at  stroom.proxy.repo.ProxyRepositoryManager.scanForOldRepositories(ProxyRepositoryManager.java:81)
at stroom.proxy.repo.ProxyRepositoryManager.start(ProxyRepositoryManaer.java43)

**Comment by stroomdev10** [comment]
repositoryFormat=${feed}/${pathId}/${id}
